/* __imports_rewritten__ */
import React from 'https://esm.sh/react@19.2.0';
import {CheckCircle2, Clock, FolderKanban, TriangleAlert, TrendingUp} from 'https://esm.sh/lucide-react?deps=react@19.2.0';
import { Link, useParams } from 'https://esm.sh/react-router-dom@7.13.0?deps=react@19.2.0';
import { html } from '../jsx.js';
import { getMetrics } from '../utils/metrics.js';
import { PageTitle, SkeletonCards, EmptyState } from '../components/UI.js';
import { useAppShell } from '../mainProviders.js';

export function Dashboard() {
  const { code } = useParams();
  const { visibleProjects, session } = useAppShell();
  const [loading, setLoading] = React.useState(true);
  const [owner, setOwner] = React.useState('All');
  React.useEffect(() => { const t = setTimeout(() => setLoading(false), 300); return () => clearTimeout(t); }, []);
  const project = code ? visibleProjects.find(p => p.code === code) : session?.role === 'Client' ? visibleProjects[0] : null;
  if (code && !project) return html`<${EmptyState} title="Project not found" detail="This client code is not available in your workspace." />`;
  if (project) return html`<${ProjectDashboard} project=${project} session=${session} />`;
  const owners = ['All', ...Array.from(new Set(visibleProjects.map(p => p.projectOwner || 'Others')))];
  const filtered = owner === 'All' ? visibleProjects : visibleProjects.filter(p => (p.projectOwner || 'Others') === owner);
  const metrics = getMetrics(filtered);
  const avg = filtered.length ? Math.round(filtered.reduce((sum, p) => sum + getMetrics([p]).progress, 0) / filtered.length) : 0;
  const cards = [{ label: 'Total Projects', value: filtered.length, icon: FolderKanban, accent: 'var(--primary)' },{ label: 'Avg Completion %', value: `${avg}%`, icon: TrendingUp, accent: 'var(--blue)' },{ label: 'Total Overdue Tasks', value: metrics.overdue, icon: TriangleAlert, accent: 'var(--red)' },{ label: 'Total Upcoming Tasks', value: metrics.upcoming, icon: Clock, accent: 'var(--yellow)' }];
  return html`<div><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><${PageTitle} eyebrow="Admin Dashboard" title="Project Directory" description="Filter projects by owner, review portfolio analytics, and open project-specific dashboards." /><${Link} to="/clients" className="rounded-2xl bg-[hsl(var(--primary))] px-4 py-3 text-sm font-semibold text-white shadow-[var(--shadow-md)]">Create New Project</${Link}></div><div className="card mb-5 flex flex-col gap-3 p-4 sm:flex-row sm:items-center sm:justify-between"><label className="text-sm font-medium">Filter by Project Owner</label><select value=${owner} onChange=${e=>setOwner(e.target.value)} className="rounded-2xl border border-[hsl(var(--border))] bg-[hsl(var(--card))] px-4 py-3 focus-ring">${owners.map(o => html`<option key=${o} value=${o}>${o}</option>`)}</select></div>${loading ? html`<${SkeletonCards} />` : html`<div><div className="mb-5 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">${cards.map((card, index) => html`<${MetricCard} key=${card.label} card=${card} index=${index} />`)}</div>${owner !== 'All' && html`<div className="card mb-5 grid gap-3 p-4 sm:grid-cols-4"><p><span className="text-xs text-[hsl(var(--muted))]">Total projects</span><br/><b>${filtered.length}</b></p><p><span className="text-xs text-[hsl(var(--muted))]">Avg progress</span><br/><b>${avg}%</b></p><p><span className="text-xs text-[hsl(var(--muted))]">Completed steps</span><br/><b>${metrics.completed}</b></p><p><span className="text-xs text-[hsl(var(--muted))]">Pending steps</span><br/><b>${metrics.pending}</b></p></div>`}${filtered.length === 0 ? html`<${EmptyState} title="No projects yet" detail="No projects match this owner filter." />` : html`<div className="grid gap-4 lg:grid-cols-2 xl:grid-cols-3">${filtered.map(p => { const m = getMetrics([p]); return html`<${Link} key=${p.code} to=${`/projects/${p.code}`} className="card card-hover block p-6"><div className="flex items-start justify-between gap-3"><div><h3 className="font-semibold">${p.projectName}</h3><p className="mt-1 text-sm text-[hsl(var(--muted))]">${p.clientName} · ${p.code}</p></div><span className="rounded-2xl bg-[hsl(var(--primary))]/10 px-3 py-2 text-sm font-semibold text-[hsl(var(--primary))]">${m.progress}%</span></div><div className="mt-5 grid gap-3 text-sm sm:grid-cols-2"><p><span className="text-xs text-[hsl(var(--muted))]">Project Owner</span><br/><b>${p.projectOwner || 'Others'}</b></p><p><span className="text-xs text-[hsl(var(--muted))]">Status summary</span><br/><b>${m.completed} Completed / ${m.pending} Pending</b></p></div></${Link}>`; })}</div>`}</div>`}</div>`;
}
function ProjectDashboard({ project, session }) { const metrics = getMetrics([project]); const cards = [{ label: 'Total Steps', value: metrics.total, icon: FolderKanban, accent: 'var(--primary)' },{ label: 'Completed Steps', value: metrics.completed, icon: CheckCircle2, accent: 'var(--green)' },{ label: 'Pending Steps', value: metrics.pending, icon: Clock, accent: 'var(--yellow)' },{ label: 'Overdue Tasks', value: metrics.overdue, icon: TriangleAlert, accent: 'var(--red)' },{ label: 'Overall Progress %', value: `${metrics.progress}%`, icon: TrendingUp, accent: 'var(--blue)' }]; return html`<div><${PageTitle} eyebrow="Project Dashboard" title=${project.projectName} description="Project-specific details, progress, alerts, and workflow tabs." />${session?.role === 'Admin' && html`<${Link} to="/" className="mb-4 inline-flex rounded-2xl border border-[hsl(var(--border))] bg-[hsl(var(--card))] px-4 py-2 text-sm font-semibold">← Back to Project Directory</${Link}>`}<div className="card mb-6 p-5"><div className="grid gap-3 md:grid-cols-5"><p><span className="text-xs text-[hsl(var(--muted))]">Client Code</span><br/><b>${project.code}</b></p><p><span className="text-xs text-[hsl(var(--muted))]">Client</span><br/><b>${project.clientName}</b></p><p><span className="text-xs text-[hsl(var(--muted))]">Project Owner</span><br/><b>${project.projectOwner || 'Others'}</b></p><p><span className="text-xs text-[hsl(var(--muted))]">Location</span><br/><b>${project.location || '-'}</b></p><p><span className="text-xs text-[hsl(var(--muted))]">Progress</span><br/><b>${metrics.progress}%</b></p></div>${project.projectDetails && html`<p className="mt-4 text-sm text-[hsl(var(--muted))]">${project.projectDetails}</p>`}</div><div className="mb-6 flex flex-wrap gap-2"><${Link} className="rounded-2xl bg-[hsl(var(--primary))] px-4 py-2 text-sm font-semibold text-white" to=${`/projects/${project.code}/process`}>Process Tracker</${Link}><${Link} className="rounded-2xl border border-[hsl(var(--border))] px-4 py-2 text-sm font-semibold" to=${`/projects/${project.code}/analytics`}>Analytics</${Link}><${Link} className="rounded-2xl border border-[hsl(var(--border))] px-4 py-2 text-sm font-semibold" to=${`/projects/${project.code}/alerts`}>Alerts</${Link}></div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5">${cards.map((card, index) => html`<${MetricCard} key=${card.label} card=${card} index=${index} />`)}</div></div>`; }
function MetricCard({ card, index }) { const Icon = card.icon; return html`<div className="card card-hover animate-rise p-5" style=${{ animationDelay: `${index * 55}ms` }}><div className="flex items-center justify-between"><div className="grid h-11 w-11 place-items-center rounded-2xl" style=${{ backgroundColor: `hsl(${card.accent} / .13)`, color: `hsl(${card.accent})` }}><${Icon} size=${20} /></div><span className="text-xs text-[hsl(var(--muted))]">Live</span></div><p className="mt-5 text-sm text-[hsl(var(--muted))]">${card.label}</p><p className="mt-1 text-3xl font-semibold tracking-tight">${card.value}</p></div>`; }